In [1]:
import numpy as np

In [6]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [7]:
# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print (ridership[1, 3])  # guess - 2328 (correct!)
    print (ridership[1:3, 3:5])  # guess - explanation below
    print (ridership[1, :])  # guess - [1478, 3877, 3674, 2328, 2539] (correct!)


2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


## But why did the second command produce such a matrix?

Well, firstly, let's have a look at the matrix, and this time, let's mark the rows.
```py
[
    [   0,    0,    2,    5,    0],  # row 0
    [1478, 3877, 3674, 2328, 2539],  # row 1
    [1613, 4088, 3991, 6461, 2691],  # row 2
    [1560, 3392, 3826, 4787, 2613],  # row 3
    [1608, 4802, 3932, 4477, 2705],  # row 4
    [1576, 3933, 3909, 4979, 2685],  # row 5
    [  95,  229,  255,  496,  201],  # row 6
    [   2,    0,    1,   27,    0],  # row 7
    [1438, 3785, 3589, 4174, 2215],  # row 8
    [1342, 4043, 4009, 4665, 3033]  # row 9
]
```

In order to answer this, break the command by the parameters within the square brackets.
- Parameter 1 - `[1:3]`
- Parameter 2 - `[3:5]`

These are essentially two consecutive slices. First will be the row slicing from 1 to 3-1, and second will be the column slicing from 3 to 5-1.

### Parameter 1 - [1:3]
`a:b` means you start at `a`th row, and slice your way down to the `b-1`th row. So in this case, the sliced array of the original array would start at row 1, and go on till row 3 - 1 = 2, resulting in the following array:
```py
#   0       1      2    3      4    <= columns
[
    [1478, 3877, 3674, 2328, 2539],  # row 1
    [1613, 4088, 3991, 6461, 2691]  # row 2
]
```
Note that this time, the columns are also marked, because they will be needed in the second slicing of parameter 2.

### Parameter 2 - [3:5]
This time, instead of slicing rows, slice the columns (that's what the second parameter is for). So we begin at column 3, and slice uptil column 5-1 = 4, resulting in the following final matrix.
```py
[
    [2328, 2539],
    [6461, 2691]
]
```

In [8]:
# Vectorized operations on rows or columns
if True:
    print (ridership[0, :] + ridership[1, :])  # guess - [0, 0, 2, 5, 0] + [1478, 3877, 3674, 2328, 2539] = [1478, 3877, 3676, 2333, 2539]
    print (ridership[:, 0] + ridership[:, 1])  # guess - column 0 + column 1


[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [19]:
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print (a + b)  # guess - normal matrix addition

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [20]:
ridership

array([[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539],
       [1613, 4088, 3991, 6461, 2691],
       [1560, 3392, 3826, 4787, 2613],
       [1608, 4802, 3932, 4477, 2705],
       [1576, 3933, 3909, 4979, 2685],
       [  95,  229,  255,  496,  201],
       [   2,    0,    1,   27,    0],
       [1438, 3785, 3589, 4174, 2215],
       [1342, 4043, 4009, 4665, 3033]])

In [27]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    max_for_first = np.argmax(ridership[0, :])
    overall_mean = ridership.mean() # Replace this with your code
    mean_for_max = (ridership[:, max_for_first]).mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [28]:
mean_riders_for_max_station(ridership)

(2342.6, 3239.9)